### PR TITLE
Add loading gif

### PR DESCRIPTION
**Pull request by neeraj-lad**

### CODE REVIEW

**Comment by clairew** [comment]
Hi Neeraj, can you explain your pull? Thanks!

**Comment by neeraj-lad** [comment]
Sorry for the lack of description.
Once the user clicks the button, there is a delay of about 1 second before the summary is displayed. I've added a [loading-icon gif](http://www.brahmavidyayoga.org/wp-content/themes/twentyfifteen/loading.gif), so that the user is notified that the processing is underway.

**Comment by clairew** [comment]
Awesome thanks!

**Comment by neeraj-lad** [comment]
You're welcome. I am glad I could contribute!

**Pull request merged**
